### ISSUE TITLE
what have you done? where is question and answer to HumHub? One that works...

### ISSUE THREAD

**Issue by ernestbuffington** [benmag/laravel-rancher#9]
Sorry for asking here but I see no other way to ask.

Shoot me an e-mail I have to have a working version for the campus. ernest.buffington@gmail.com

Are you no longer working on HumHub?

**Comment by benmag** [comment]
Hi ernestbuffington 

The 'question and answer' module I was involved with is no longer maintained

The code is still available here: https://github.com/ConnectedCommunities/humhub-modules-questionanswer 

Unfortunately, I am not sure if anyone in the open source community has continued to work on anything similar
